kind: PersistentVolume
apiVersion: v1
metadata:
  name: models-1-0-0
  namespace: full-stack
  labels:
    app: models-1-0-0
spec:
  capacity:
    storage: 3Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: full-stack
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

