apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: full-stack
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
